import { JoinSection } from '@components/homePage/JoinSection';
import { MinNavBar } from '@components/MinNavBar';
import { NavBar } from '@components/NavBar';
import { Slider } from '@components/homePage/Slider';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { BrowseProfessionals } from '@components/homePage/BrowseProfessionals';
import { ShopByCategory } from '@components/homePage/ShopByCategory';
import { Separator } from '@components/homePage/Separator';
import { BrowseByStyle } from '@components/homePage/BrowseByStyle';
import { LatestStories } from '@components/homePage/LatestStories';
import { UpcomingEvents } from '@components/homePage/UpcomingEvents';
import { GetStarted } from '@components/homePage/GetStarted';
import { NewsLetter } from '@components/homePage/NewsLetter';
import { Footer } from '@components/Footer';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hanger</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<MinNavBar />
				<NavBar />
				<Slider />
				<JoinSection />
				<BrowseProfessionals />
				<Separator />
				<ShopByCategory />
				<Separator />
				<BrowseByStyle />
				<Separator />
				<LatestStories />
				<UpcomingEvents />
				<GetStarted />
				<NewsLetter />
				<Footer />
			</div>
		</>
	);
};

export default Home;
